<template>
    <div class="q-ma-md" v-if="tripCatch">
        <div class="text-h4 bg-primary text-white" style="border-radius: 5px; padding: 10px; margin: 5px">
            <q-icon name="fa fa-ship"/>
            Trip {{tripCatch.tripNum}}
            <span v-if="selectedHaul">
                &nbsp;
                <q-icon name="fa fa-layer-group"/>
                Haul {{ selectedHaul }}
            </span>
            <span v-if="selectedCatch">
                &nbsp;
                <q-icon name="fa fa-fish"/>
                {{ tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].speciesCode }} -
                {{ tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].catchDisposition }}
            </span>
        </div>
        <q-expansion-item
            class="text-primary"
            expand-separator
            icon="fa fa-ship"
            label="Trip Details"
            default-opened
        >
        <div class="row items-start">
            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                <div class="text-h4 text-grey-7">Trip</div>
                <q-field v-model="tripCatch.tripNum" outlined dense autogrow title="Unique 6 digit Trip id - generated by Trips API">
                    <template v-slot: control>
                        <div class="self-center full-width no-outline text-black text-bold" tabindex="0">{{ tripCatch.tripNum }}</div>
                    </template>
                    <template v-slot:append>
                        <div class="text-h6">Trip #</div>
                        </template>
                </q-field>

                <q-input v-model="tripCatch.year" outlined dense autogrow title="Year the fishing activity took place">
                    <template v-slot:append>
                        <div class="text-h6">Year</div>
                    </template>
                </q-input>

                <q-input v-model="tripCatch.logbookPageNumber" outlined dense autogrow title="Page number from vessel logbook" mask="#####">
                    <template v-slot:append>
                        <div class="text-h6">Logbook Page #</div>
                    </template>
                </q-input>

                <q-select v-model="tripCatch.fishery" outlined dense autogrow title="Description of the EM fishery. Whiting, Midwater Rockfish, Fixed Gear, Bottom Trawl" :options="fisheryOptions">
                    <template v-slot:append>
                        <div class="text-h6">Fishery</div>
                    </template>
                </q-select>
                <br><br>
            </div>

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px">
                <div class="text-h4 text-grey-7">Vessel</div>
                <q-input v-model="tripCatch.vesselName" outlined dense autogrow title="Name of the fishing vessel">
                    <template v-slot:append>
                        <div class="text-h6">Name</div>
                    </template>
                </q-input>

                <q-input v-model="tripCatch.vesselNumber" outlined dense autogrow title="Vessel Coast Guard or State Reg Number">
                    <template v-slot:append>
                        <div class="text-h6">Number</div>
                    </template>
                </q-input>

                <q-input v-model="tripCatch.permitNumber" outlined dense autogrow title="Limited Entry permit number (GF0000)">
                    <template v-slot:append>
                        <div class="text-h6">Permit Number</div>
                    </template>
                </q-input>

                <q-input v-model="tripCatch.skipperName" outlined dense autogrow title="Name of the vessel captain">
                    <template v-slot:append>
                        <div class="text-h6">Skipper</div>
                    </template>
                </q-input>

                <q-input v-model="tripCatch.crewSize" outlined dense title="Total number of crew on board the vessel">
                    <template v-slot:append>
                        <div class="text-h6">Crew Size</div>&nbsp;
                        <q-btn round size="sm" icon="add" @click="tripCatch.crewSize += 1"></q-btn>
                        <q-btn round size="sm" icon="remove" @click="tripCatch.crewSize -= 1"></q-btn>
                    </template>
                </q-input>
            </div>

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px">
                <div class="text-h4 text-grey-7">Departure</div>
                <div class="row items-start">
                    <q-field v-model="tripCatch.departureDateTime" outlined dense autogrow title="Date/Time the vessel departed port"  style="width: 55%; margin-right: 5px">
                        <template v-slot:control>
                            {{ formatDate(tripCatch.departureDateTime) }}
                        </template>
                        <template v-slot:prepend>
                            <q-icon name="edit" class="cursor-pointer">
                            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                                <q-date v-model="tripCatch.departureDateTime" @input="() => {departureTime = '', $refs.qDateProxy.hide()}"/>
                            </q-popup-proxy>
                            </q-icon>
                        </template>
                        <template v-slot:append>
                            <div class="text-h6">Date</div>
                        </template>
                    </q-field>

                    <q-input v-model="departureTime" outlined dense autogrow title="Time the vessel departed port" mask="##:##" :rules="[val => val.split(':')[0] < 24 || 'invalid hour', val => val.split(':')[1] < 60 || 'invalid minute']" style="width: 43.3%">
                        <template v-slot:append>
                            <div class="text-h6">Time</div>
                        </template>
                    </q-input>
                </div>
                <div class="row items-start">
                    <q-select v-model="tripCatch.departureState" outlined dense autogrow title="State where the vessel departed for fishing activities (WA, OR, CA)" style="width: 42%; margin-right: 5px" :options="['CA','OR', 'WA']">
                        <template v-slot:append>
                            <div class="text-h6">State</div>
                        </template>
                    </q-select>

                    <q-input v-model="tripCatch.departurePortCode" outlined dense autogrow title="Port code where the vessel departed. The port code is the same as the PacFIN port code" style="width: 56.3%" mask="XXXX">
                        <template v-slot:append>
                            <div class="text-h6">Port Code</div>
                        </template>
                    </q-input>
                </div>
                <hr size="2" noshade>
                <div class="text-h4 text-grey-7" style="text-align: right">Return</div>
                <div class="row items-start">
                    <q-field v-model="tripCatch.returnDateTime" outlined dense autogrow title="Date/Time the vessel returned to port for offload" style="width: 55%; margin-right: 5px">
                        <template v-slot:control>
                            {{ formatDate(tripCatch.returnDateTime) }}
                        </template>
                        <template v-slot:prepend>
                            <q-icon name="edit" class="cursor-pointer">
                            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                                <q-date v-model="tripCatch.returnDateTime" @input="() => {returnTime = '', $refs.qDateProxy.hide()}"/>
                            </q-popup-proxy>
                            </q-icon>
                        </template>
                        <template v-slot:append>
                            <div class="text-h6">Date</div>
                        </template>
                    </q-field>
                    <q-input v-model="returnTime" outlined dense autogrow title="Time the vessel returned to port" mask="##:##" :rules="[val => val.split(':')[0] < 24 || 'invalid hour', val => val.split(':')[1] < 60 || 'invalid minute']" style="width: 43.3%">
                        <template v-slot:append>
                            <div class="text-h6">Time</div>
                        </template>
                    </q-input>
                </div>
                <div class="row items-start">
                    <q-select v-model="tripCatch.returnPortState" outlined dense autogrow title="State where the vessel returned for fishing activities (WA, OR, CA)" style="width: 42%; margin-right: 5px" :options="['CA', 'OR', 'WA']">
                        <template v-slot:append>
                            <div class="text-h6">State</div>
                        </template>
                    </q-select>

                    <q-input v-model="tripCatch.returnPortCode" outlined dense autogrow title="Port code where the vessel returned. The port code is the same as the PacFIN port code" style="width: 56.3%" mask="XXXX">
                        <template v-slot:append>
                            <div class="text-h6">Port Code</div>
                        </template>
                    </q-input>
                </div>
            </div>

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px">
                <div class="text-h4 text-grey-7">Details</div>
                <q-field v-model="tripCatch.isEFPTrip" class="text-primary" outlined dense autogrow title="Y/N flag indicating if the trip was an EFP trip">
                    <template v-slot:append>
                        <div class="text-h6">EFP Trip?</div>&nbsp;
                        <q-btn :class="getClass('isEFPTrip', 'yes')" size="sm" label="Yes" @click="tripCatch.isEFPTrip = true"></q-btn>
                        <q-btn :class="getClass('isEFPTrip', 'no')" size="sm" label="No" @click="tripCatch.isEFPTrip = false"></q-btn>
                    </template>
                </q-field>

                <q-field v-model="tripCatch.isObserved" class="text-primary" outlined dense autogrow title="Y/N flag indicating if a scientific observer was on board">
                    <template v-slot:append>
                        <div class="text-h6">Observed?</div>&nbsp;
                        <q-btn :class="getClass('isObserved', 'yes')" size="sm" label="Yes" @click="tripCatch.isObserved = true"></q-btn>
                        <q-btn :class="getClass('isObserved', 'no')" size="sm" label="No" @click="tripCatch.isObserved = false"></q-btn>
                    </template>
                </q-field>

                <q-field v-model="tripCatch.isSigned" class="text-primary" outlined dense autogrow title="Y/N flag inidicating if the logbook was signed">
                    <template v-slot:append>
                        <div class="text-h6">Is Signed?</div>&nbsp;
                        <q-btn :class="getClass('isSigned', 'yes')" size="sm" label="Yes" @click="tripCatch.isSigned = true"></q-btn>
                        <q-btn :class="getClass('isSigned', 'no')" size="sm" label="No" @click="tripCatch.isSigned = false"></q-btn>
                    </template>
                </q-field>

                <q-field v-model="tripCatch.isVoid" class="text-primary" outlined dense autogrow title="Y/N flag inidicating if the logbook is void" disabled>
                    <template v-slot:append>
                        <div class="text-h6">Void?</div>&nbsp;
                        <q-btn :class="getClass('isVoid', 'yes')" size="sm" label="Yes" @click="tripCatch.isVoid = true"></q-btn>
                        <q-btn :class="getClass('isVoid', 'no')" size="sm" label="No" @click="tripCatch.isVoid = false"></q-btn>
                    </template>
                </q-field>
                <q-input v-model="tripCatch.comment" outlined dense autogrow title="Notes from the logbook">
                    <template v-slot:append>
                        <div class="text-h6">Comment</div>
                    </template>
                </q-input>
            </div>


            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px">
                <div class="text-h4 text-grey-7">Landings</div>

                <div style="border: 2px solid grey; border-radius: 5px; padding: 10px; margin-bottom: 5px">
                    <div class="text-h6 text-grey-7">Buyers
                        <span style="float: right">
                            <q-btn flat icon="add" color="primary" @click="tripCatch.buyers.push('')"></q-btn>
                        </span>
                    </div>
                    <br>
                    <div v-for="(buyer, i) in tripCatch.buyers" :key="i">
                        <q-input v-model="tripCatch.buyers[i]" outlined dense autogrow title="IFQ Dealer where the vessel offloaded">
                            <q-btn flat dense icon="close" @click="tripCatch.buyers.splice(i , 1)"></q-btn>
                        </q-input>
                    </div>
                </div>

                <div style="border: 2px solid grey; border-radius: 5px; padding: 10px; margin-bottom: 5px">
                    <div class="text-h6 text-grey-7">Fish Tickets
                        <span style="float: right">
                            <q-btn flat icon="add" color="primary" @click="tripCatch.fishTicketNumber.push('')"></q-btn>
                        </span>
                    </div>
                    <br>
                    <div v-for="(fishTicket, i) in tripCatch.fishTicketNumber" :key="i">
                        <q-input v-model="tripCatch.fishTicketNumber[i]" outlined dense autogrow title="fish ticket number from the deleivery">
                            <q-btn flat dense icon="close" @click="tripCatch.fishTicketNumber.splice(i , 1)"></q-btn>
                        </q-input>
                    </div>
                </div>

                <q-field v-model="tripCatch.fishTicketDate" outlined dense autogrow title="Date/Time the vessel returned to port for offload">
                    <template v-slot:control>
                        {{ formatDate(tripCatch.fishTicketDate) }}
                    </template>
                    <template v-slot:prepend>
                        <q-icon name="edit" class="cursor-pointer">
                        <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                            <q-date v-model="tripCatch.fishTicketDate" @input="() => $refs.qDateProxy.hide()"/>
                        </q-popup-proxy>
                        </q-icon>
                    </template>
                    <template v-slot:append>
                        <div class="text-h6">Fish Ticket Date</div>
                    </template>
                </q-field>
            </div>

        </div>
        </q-expansion-item>

        <q-expansion-item
            expand-separator
            class="text-primary"
            icon="fa fa-layer-group"
            label="Hauls"
            default-opened
        >
        <div>
            <q-btn color="primary" @click="addHaul">Add Haul</q-btn>
            <br><br>
            <div v-if="tripCatch.hauls">
                <div v-for="(haul, i) in tripCatch.hauls.slice().reverse()" :key="i">
                    <q-field v-model="tripCatch.hauls[i]" outlined dense autogrow @click.native="selectHaul(tripCatch.hauls.indexOf(haul) + 1)">
                        <template v-slot: control>
                            <div class="self-center full-width no-outline text-black text-bold" tabindex="0">HAUL {{ tripCatch.hauls.indexOf(haul) + 1 }}
                                <span v-if="haul.startDateTime || haul.startDepth || haul.startLatitude || haul.startLongitude"> - START: </span>
                                <span v-if="haul.startDateTime"> {{ formatDateTime(haul.startDateTime) }}</span>
                                <span v-if="haul.endDateTime || haul.endDepth || haul.endLatitude || haul.endLongitude"> / END: </span>
                                <span v-if="haul.endDateTime"> {{ formatDateTime(haul.endDateTime) }}</span>
                            </div>
                        </template>
                        <template v-slot:append>
                        <q-btn flat dense icon="close" @click="tripCatch.hauls.splice(tripCatch.hauls.indexOf(haul) , 1)"></q-btn>
                        </template>
                    </q-field>
                </div>
            </div>
            <br>

        <div v-if="selectedHaul" style="border: 2px solid grey; border-radius: 5px; padding: 10px; margin-bottom: 10px">
            <div class="text-h4 text-grey-7">Haul {{ selectedHaul }}</div>
            <div class="row items-start">

            <!-- <q-input v-model="tripCatch.hauls[selectedHaul - 1].deliveryDate" outlined dense autogrow title="Date and time the vessel offloaded to a buyer">
                <template v-slot:append>
                    <div class="text-h6">Delivery Date</div>
                </template>
            </q-input> -->

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                <div class="text-h4 text-grey-7">Gear</div>
                <q-select v-model="tripCatch.hauls[selectedHaul - 1].gearTypeCode" outlined dense autogrow title="1  = Groundfish trawl, footrope < 8 inches (small footrope)  , 2  = Groundfish trawl, footrope > 8 inches (large footrope), 10 = pot, 19 = hook & line" :options="['1  = Groundfish trawl, footrope < 8 inches (small footrope)'  , '2  = Groundfish trawl, footrope > 8 inches (large footrope)', '10 = pot', '19 = hook & line']">
                    <template v-slot:append>
                        <div class="text-h6">Gear Type</div>
                    </template>
                </q-select>
                <q-select v-model="tripCatch.hauls[selectedHaul - 1].gearTypeDescription" outlined dense autogrow title="1  = Groundfish trawl, footrope < 8 inches (small footrope)  , 2  = Groundfish trawl, footrope > 8 inches (large footrope), 10 = pot, 19 = hook & line" :options="gearTypeOptions">
                    <template v-slot:append>
                        <div class="text-h6">Gear Type Description</div>
                    </template>
                </q-select>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].gearPerSet" outlined dense autogrow title="Total number of pots or hooks set (Mandatory for FG hauls)" mask="###">
                    <template v-slot:append>
                        <div class="text-h6">Gear Per Set</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].gearLost" outlined dense autogrow title="Number of pots or hooks lost (Mandatory for FG hauls)" mask="###">
                    <template v-slot:append>
                        <div class="text-h6">Gear Lost</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].avgHooksPerSeg" outlined dense autogrow title="Average hooks per set" mask="###">
                    <template v-slot:append>
                        <div class="text-h6">Avg Hooks Per Set</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].netType" outlined dense autogrow title="1  = Groundfish trawl, footrope < 8 inches (small footrope)  , 2  = Groundfish trawl, footrope > 8 inches (large footrope)" mask="" hint="1  = Groundfish trawl, footrope < 8 inches (small footrope)  , 2  = Groundfish trawl, footrope > 8 inches (large footrope)" style="margin-bottom: 15px">
                    <template v-slot:append>
                        <div class="text-h6">Net Type</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].codendCapacity" outlined dense autogrow title="Total estimated weight (lbs) the codened can hold" mask="#####">
                    <template v-slot:append>
                        <div class="text-h6">Codend Capacity</div>
                    </template>
                </q-input>
            </div>

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                <div class="text-h4 text-grey-7">Haul Start</div>
                <div class="row items-start">
                    <q-field v-model="tripCatch.hauls[selectedHaul - 1].startDateTime" outlined dense autogrow title="Date and time the gear was set" style="width: 55%; margin-right: 5px">
                        <template v-slot:control>
                            {{ formatDate(tripCatch.hauls[selectedHaul - 1].startDateTime) }}
                        </template>
                        <template v-slot:prepend>
                            <q-icon name="edit" class="cursor-pointer">
                            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                                <q-date v-model="tripCatch.hauls[selectedHaul - 1].startDateTime" @input="() => {$refs.qDateProxy.hide()}"/>
                            </q-popup-proxy>
                            </q-icon>
                        </template>
                        <template v-slot:append>
                            <div class="text-h6">Date</div>
                        </template>
                    </q-field>
                    <q-input v-model="haulStartTime" outlined dense autogrow title="Date and time the gear was set" mask="##:##" :rules="[val => val.split(':')[0] < 24 || 'invalid hour', val => val.split(':')[1] < 60 || 'invalid minute']" style="width: 43.3%">
                        <template v-slot:append>
                            <div class="text-h6">Time</div>
                        </template>
                    </q-input>
                </div>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].startDepth" outlined dense autogrow title="Depth of fishing gear when gear is deployed (Fathoms)" mask="#####">
                    <template v-slot:append>
                        <div class="text-h6">Depth</div>
                    </template>
                </q-input>
                <div class="row items-start">
                    <q-input v-model="tripCatch.hauls[selectedHaul - 1].startLatitude" outlined dense autogrow title="Latitude of gear deployement in decimal degrees" style="width: 50%; margin-right: 5px" mask="N###.######">
                        <template v-slot:append>
                            <div class="text-h6">Lat</div>
                        </template>
                    </q-input>
                    <q-input v-model="tripCatch.hauls[selectedHaul - 1].startLongitude" outlined dense autogrow title="Longitude of gear deployement in decimal degrees" style="width: 48.3%" mask="N###.######">
                        <template v-slot:append>
                            <div class="text-h6">Long</div>
                        </template>
                    </q-input>
                </div>
                <hr size=2 noshade>
                <div class="text-h4 text-grey-7" style="text-align: right">Haul End</div>
                <div class="row items-start">
                    <q-field v-model="tripCatch.hauls[selectedHaul - 1].endDateTime" outlined dense autogrow title="Date the gear was retrieved" style="width: 55%; margin-right: 5px">
                        <template v-slot:control>
                            {{ formatDate(tripCatch.hauls[selectedHaul - 1].endDateTime) }}
                        </template>
                        <template v-slot:prepend>
                            <q-icon name="edit" class="cursor-pointer">
                            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                                <q-date v-model="tripCatch.hauls[selectedHaul - 1].endDateTime" @input="() => {$refs.qDateProxy.hide()}"/>
                            </q-popup-proxy>
                            </q-icon>
                        </template>
                        <template v-slot:append>
                            <div class="text-h6">Date</div>
                        </template>
                    </q-field>
                    <q-input v-model="haulEndTime" outlined dense autogrow title="Time the gear was retrieved" mask="##:##" :rules="[val => val.split(':')[0] < 24 || 'invalid hour', val => val.split(':')[1] < 60 || 'invalid minute']" style="width: 43.3%">
                        <template v-slot:append>
                            <div class="text-h6">Time</div>
                        </template>
                    </q-input>
                </div>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].endDepth" outlined dense autogrow title="Depth of fishing gear when gear is retrieved (Fathoms)" mask="#####">
                    <template v-slot:append>
                        <div class="text-h6">Depth</div>
                    </template>
                </q-input>
                <div class="row items-start">
                    <q-input v-model="tripCatch.hauls[selectedHaul - 1].endLatitude" outlined dense autogrow title="Latitude of gear retrieval in decimal degrees" style="width: 50%; margin-right: 5px" mask="N###.######">
                        <template v-slot:append>
                            <div class="text-h6">Lat</div>
                        </template>
                    </q-input>
                    <q-input v-model="tripCatch.hauls[selectedHaul - 1].endLongitude" outlined dense autogrow title="Longitude of gear retrieval in decimal degrees" style="width: 48.3%" mask="N###.######">
                        <template v-slot:append>
                            <div class="text-h6">Long</div>
                        </template>
                    </q-input>
                </div>
            </div>

            <div class="logbook-element" style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                <div class="text-h4 text-grey-7">Details</div>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].targetStrategy" outlined dense autogrow title="Target Fish">
                    <template v-slot:append>
                        <div class="text-h6">Target Strategy</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].avgDepth" outlined dense autogrow title="Average Depth (in Fathoms)">
                    <template v-slot:append>
                        <div class="text-h6">Average Depth</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].systemPerformance" outlined dense autogrow title="1 = No issues, 2 = Video Gaps, 3 = Poor video quality" mask="#">
                    <template v-slot:append>
                        <div class="text-h6">System Performance</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].catchHandlingPerformance" outlined dense autogrow title="1 = No issues, 2 = Issues" mask="#">
                    <template v-slot:append>
                        <div class="text-h6">Catch Handling Performance</div>
                    </template>
                </q-input>
                <q-input v-model="tripCatch.hauls[selectedHaul - 1].comments" outlined dense autogrow title="Notes pertaining to a specific haul record">
                    <template v-slot:append>
                        <div class="text-h6">Comments</div>
                    </template>
                </q-input>
            </div>
            </div>
                <q-expansion-item
                    v-if="selectedHaul"
                    expand-separator
                    class="text-primary"
                    icon="fa fa-fish"
                    label="Catch"
                    default-opened
                >
                    <div style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                        <q-btn color="primary" @click="addCatch">Add Catch</q-btn>
                        <br><br>
                        <div v-if="selectedHaul && tripCatch.hauls[selectedHaul - 1].catch">
                        <div v-for="(fish, i) in tripCatch.hauls[selectedHaul - 1].catch.slice().reverse()" :key="i">
                            <q-field v-model="tripCatch.hauls[selectedHaul - 1].catch[tripCatch.hauls[selectedHaul - 1].catch.indexOf(fish)]" outlined dense autogrow @click.native="selectedCatch = tripCatch.hauls[selectedHaul -1].catch.indexOf(fish) + 1">
                                <template v-slot:control>
                                    <div class="self-center full-width no-outline text-black text-bold" tabindex="0">
                                        <span v-if="fish.speciesCode">{{ fish.speciesCode }}</span>
                                        <span v-if="fish.catchDisposition"> - {{ fish.catchDisposition }}</span>
                                        <span v-if="fish.estimatedWeight"> - {{ fish.estimatedWeight }} lbs</span>
                                    </div>
                                </template>
                                <template v-slot:append>
                                    <q-btn flat dense icon="close" @click="tripCatch.hauls[selectedHaul - 1].catch.splice(tripCatch.hauls[selectedHaul - 1].catch.indexOf(fish) , 1)"></q-btn>
                                </template>
                            </q-field>
                        </div>
                        <br>
                        </div>
                        <div v-if="selectedCatch" style="border: 2px solid grey; border-radius: 5px; padding: 10px;">
                            <div class="text-h4 text-grey-7">
                                {{ tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].speciesCode }} -
                                {{ tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].catchDisposition }}
                            </div>
                            <div class="row items-start">
                                <q-select  class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].catchDisposition" outlined dense autogrow title="Disposition of the Catch (Retained or Discard)" :options="['Discarded', 'Retained']">
                                    <template v-slot:append>
                                        <div class="text-h6">Catch Disposition</div>
                                    </template>
                                </q-select>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].speciesCode" outlined dense autogrow title="WCGOP species code (3 or 4 digits)" mask="XXXX">
                                    <template v-slot:append>
                                        <div class="text-h6">Species Code</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].estimatedWeight" outlined dense autogrow title="Estimated weight in lbs" mask="#####">
                                    <template v-slot:append>
                                        <div class="text-h6">Estimated Total Weight</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].catchCount" outlined dense autogrow title="Number of fish for a species (Yellow Eye RF, PHLB, Species of concern...Salmon, Green Sturgeon, Eulachon). Not required for all species" mask="###">
                                    <template v-slot:append>
                                        <div class="text-h6">Count</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].calcWeightType" outlined dense autogrow title="Description of how the catch was calculated (EstWeight, FromAverageWt, FromLength, CaclField)">
                                    <template v-slot:append>
                                        <div class="text-h6">Weight Calculation Method</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].length" outlined dense autogrow title="Length (in cm) of individual fish (Pacific Halibut)" mask="####">
                                    <template v-slot:append>
                                        <div class="text-h6">Length</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].timeOnDeck" outlined dense autogrow title="Time on deck (in min) specific to each Pacific Halibut" mask="###">
                                    <template v-slot:append>
                                        <div class="text-h6">timeOnDeck</div>
                                    </template>
                                </q-input>
                                <q-input class="logbook-element" v-model="tripCatch.hauls[selectedHaul - 1].catch[selectedCatch - 1].comments" outlined dense autogrow title="Notes pertaining to a specific catch record">
                                    <template v-slot:append>
                                        <div class="text-h6">Comments</div>
                                    </template>
                                </q-input>

                            </div>
                        </div>
                    </div>
                </q-expansion-item>
            </div>
        </div>
        </q-expansion-item>

    </div>
</template>

<script lang="ts">
import {
  createComponent,
  ref,
  reactive,
  computed,
  watch,
  onBeforeUnmount,
  onMounted,
  onServerPrefetch
} from '@vue/composition-api';
import { Vue, Watch } from 'vue-property-decorator';
import { CouchDBInfo, CouchDBCredentials, couchService } from '@boatnet/bn-couch';
import { Client, CouchDoc, ListOptions } from 'davenport';
import { WatchOptions } from 'vue';

import { Notify } from 'quasar';
import moment from 'moment';

import Calendar from 'primevue/calendar';
Vue.component('pCalendar', Calendar);

import { getTripsApiTrip, getCatchApiCatch } from '@boatnet/bn-common';

export default createComponent({
  setup(props, context) {
    const store = context.root.$store;
    const state = store.state;
    const selectedHaul: any = ref(null);
    const selectedCatch: any = ref(null);

    const tripCatch: any = reactive({});

    const getClass = (attribute: any, option: string) => {
        if (option === 'yes') {
            if (tripCatch[attribute]) {
                return 'bg-primary text-white';
            } else {
                return 'bg-secondary text-white';
            }
        } else {
            if (!tripCatch[attribute]) {
                return 'bg-primary text-white';
            } else {
                return 'bg-secondary text-white';
            }
        }
    };

    const addCatch = () => {
        if (!tripCatch.hauls[selectedHaul.value - 1].catch) {
            Vue.set(tripCatch.hauls[selectedHaul.value - 1], 'catch', []);
        }
        tripCatch.hauls[selectedHaul.value - 1].catch.push({});
        selectedCatch.value = tripCatch.hauls[selectedHaul.value - 1].catch.length;
    };

    const addHaul = () => {
        tripCatch.hauls.push( {startDateTime: moment().format(), endDateTime: moment().format()} );
        selectedCatch.value = null;
        selectedHaul.value = tripCatch.hauls.length;
        haulStartTime.value = moment(tripCatch.hauls[selectedHaul.value -1].startDateTime).format('hh:mm');
        haulEndTime.value = moment(tripCatch.hauls[selectedHaul.value -1].endDateTime).format('hh:mm');
    };

    const selectHaul = (haulIndex: number) => {
        selectedHaul.value = haulIndex;
        selectedCatch.value = null;
        haulStartTime.value = moment(tripCatch.hauls[selectedHaul.value -1].startDateTime).format('hh:mm');
        haulEndTime.value = moment(tripCatch.hauls[selectedHaul.value -1].endDateTime).format('hh:mm');
    };

    const fisheryOptions: any = [];
    const getFisheryOptions = async () => {
        const masterDb = couchService.masterDB;
        const queryOptions = {
        reduce: false,
        include_docs: true,
        key: 'fishery'
        };

        const fisheries = await masterDb.view(
        'obs_web',
        'all_doc_types',
        queryOptions,
        );

        const fisheryOptionsRows = fisheries.rows.map((row: any) => row.doc.description);
        for (const row of fisheryOptionsRows) {
            fisheryOptions.push(row);
        }

        fisheryOptions.sort( (a: any, b: any) => {
        if (a > b) {
            return 1;
        } else if (a < b) {
            return -1;
        } else {
            return 0;
        }
        });
    };

    const gearTypeOptions: any = [];
    const getGearTypeOptions = async () => {
        const masterDb = couchService.masterDB;
        const queryOptions = {
        reduce: false,
        include_docs: true,
        key: 'gear-type'
        };

        const gearTypes = await masterDb.view(
        'obs_web',
        'all_doc_types',
        queryOptions,
        );

        const gearTypeOptionsRows = gearTypes.rows.map((row: any) => row.doc.description);
        for (const row of gearTypeOptionsRows) {
            gearTypeOptions.push(row);
        }

        gearTypeOptions.sort( (a: any, b: any) => {
        if (a > b) {
            return 1;
        } else if (a < b) {
            return -1;
        } else {
            return 0;
        }
        });
    };

    const getCatch = async (id: any) => {
        await getCatchApiCatch(id).then(
            (res: any) => {
                for (const key of Object.keys(res[0])) {
                    Vue.set(tripCatch, key, res[0][key]);
                }
            }
        );
    };

    const formatDateTime = (val: any) => {
        return moment(val).format('MMM, DD, YYYY HH:mm');
    };

    const formatDate = (val: any) => {
        return moment(val).format('MMM, DD, YYYY');
    };

    const watcherOptions: WatchOptions = {
      immediate: false
    };

    let departureTime: any = ref(0);
    const getDepartureTime = () => {
        departureTime.value = moment(tripCatch.departureDateTime).format('hh:mm');
    }
    watch(
        () => {return departureTime.value},
        (newVal, oldVal) => {
            const departureDate = moment(tripCatch.departureDateTime)
            if (newVal && newVal.indexOf(':') !== -1) {
                departureDate.set('hour', newVal.split(':')[0]);
                departureDate.set('minute', newVal.split(':')[1]);
                tripCatch.departureDateTime = departureDate.format();
            }
        },
        watcherOptions
    )

    let returnTime: any = ref(0);
    const getReturnTime = () => {
        returnTime.value = moment(tripCatch.returnDateTime).format('hh:mm');
    }
    watch(
        () => {return returnTime.value},
        (newVal, oldVal) => {
            const returnDate = moment(tripCatch.returnDateTime)
            if (newVal && newVal.indexOf(':') !== -1) {
                returnDate.set('hour', newVal.split(':')[0]);
                returnDate.set('minute', newVal.split(':')[1]);
                tripCatch.returnDateTime = returnDate.format();
            }
        },
        watcherOptions
    )

    let haulStartTime: any = ref([]);
    watch(
        () => {return haulStartTime.value},
        (newVal, oldVal) => {
            if (newVal && newVal.indexOf(':') !== -1) {
                const startDate = moment(tripCatch.hauls[selectedHaul.value -1].startDateTime);
                startDate.set('hour', newVal.split(':')[0]);
                startDate.set('minute', newVal.split(':')[1]);
                tripCatch.hauls[selectedHaul.value -1].startDateTime = startDate.format();
            }
        },
        watcherOptions
    )

    let haulEndTime: any = ref([]);
    watch(
        () => {return haulEndTime.value},
        (newVal, oldVal) => {
            if (newVal && newVal.indexOf(':') !== -1) {
                const endDate = moment(tripCatch.hauls[selectedHaul.value -1].endDateTime);
                endDate.set('hour', newVal.split(':')[0]);
                endDate.set('minute', newVal.split(':')[1]);
                tripCatch.hauls[selectedHaul.value -1].endDateTime = endDate.format();
            }
        },
        watcherOptions
    )

    onMounted( () => {
        getFisheryOptions();
        getGearTypeOptions();
        if (context.root.$route.params.id === 'new') {
            const dummyTrip: any = {
                tripNum: '00000',
                crewSize: 0,
                year: moment().format('YYYY'),
                isEFPTrip: false,
                isObserved: false,
                isSigned: true,
                isVoid: false,
                buyers: [],
                fishTicketNumber: [],
                hauls: [],
                departureDateTime: moment().format(),
                returnDateTime: moment().format()
            };

            for (const key of Object.keys(dummyTrip)) {
                Vue.set(tripCatch, key, dummyTrip[key]);
            }
            setTimeout( () => {
                getDepartureTime();
                getReturnTime();
            }, 500)
        } else {
            getCatch(context.root.$route.params.id).then(
                () => {
                    getDepartureTime();
                    getReturnTime();
                }
            );
        }

    }
    );

    return {
        tripCatch,
        addCatch,
        addHaul,
        selectHaul,
        getClass,
        selectedHaul,
        selectedCatch,
        fisheryOptions,
        gearTypeOptions,
        formatDateTime,
        formatDate,
        departureTime,
        returnTime,
        haulStartTime,
        haulEndTime
    };
  }
});
</script>

<style>

body .p-inputtext {
    border-radius: 4px !important;
    background-color: #c8c8c8 !important;
}

.logbook-element {
  width: 100%;
  max-width: 350px;
  margin: 3px
}

</style>